In [1]:
import os
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
# raw_data directory
raw_data_path = "../Data/raw_data"
# Initialize an empty list to store DataFrames
df_list = []

# Use os.walk to traverse the directory and find all CSV files
for root, dirs, files in os.walk(raw_data_path):
    for file in files:
        if file.endswith(".csv"):
            print(f"Found file: {file}")  # Confirm files are found
            # Get the full file path
            file_path = os.path.join(root, file)
            # Read the CSV file into a DataFrame and add it to the list
            df_list.append(pd.read_csv(file_path))



# Check if df_list is empty before concatenating
if df_list:
    # Concatenate all DataFrames into one
    combined_df = pd.concat(df_list, ignore_index=True)
    print("All CSV files have been successfully read into a single DataFrame.")
else:
    print("No CSV files found in the directory.")

# display the first few rows of the combined DataFrame
combined_df.head()

Found file: 2023-01-cleveland-street.csv
Found file: 2023-02-cleveland-street.csv
Found file: 2023-03-cleveland-street.csv
Found file: 2023-04-cleveland-street.csv
Found file: 2023-05-cleveland-street.csv
Found file: 2023-06-cleveland-street.csv
Found file: 2023-07-cleveland-street.csv
Found file: 2023-08-cleveland-street.csv
Found file: 2023-09-cleveland-street.csv
Found file: 2023-10-cleveland-street.csv
Found file: 2023-11-cleveland-street.csv
Found file: 2023-12-cleveland-street.csv
Found file: 2024-01-cleveland-street.csv
Found file: 2024-02-cleveland-street.csv
Found file: 2024-03-cleveland-street.csv
Found file: 2024-04-cleveland-street.csv
Found file: 2024-05-cleveland-street.csv
Found file: 2024-06-cleveland-street.csv
All CSV files have been successfully read into a single DataFrame.

,Crime ID,Month,Reported by,Falls within,Longitude,Latitude,Location,LSOA code,LSOA name,Crime type,Last outcome category,Context
0,a4c83212c5e08e368dc841371fc26a62f7a476d19dd836...,2023-01,Cleveland Police,Cleveland Police,-1.212283,54.506084,On or near Bromley Lane,E01027626,Hambleton 002D,Other theft,Investigation complete; no suspect identified,NaN
1,NaN,2023-01,Cleveland Police,Cleveland Police,-1.235660,54.710526,On or near Dobson Place,E01011954,Hartlepool 001A,Anti-social behaviour,NaN,NaN
2,NaN,2023-01,Cleveland Police,Cleveland Police,-1.237805,54.711196,On or near King Oswy Shops,E01011954,Hartlepool 001A,Anti-social behaviour,NaN,NaN
3,NaN,2023-01,Cleveland Police,Cleveland Police,-1.236325,54.713146,On or near Lazenby Road,E01011954,Hartlepool 001A,Anti-social behaviour,NaN,NaN
4,c108d52a0f5bb4dd8e7f50ad9bd75e583a0a0d2ab1d1ee...,2023-01,Cleveland Police,Cleveland Police,-1.239865,54.710589,On or near Marshall Close,E01011954,Hartlepool 001A,Burglary,Investigation complete; no suspect identified,NaN

In [3]:
combined_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 142284 entries, 0 to 142283
Data columns (total 12 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Crime ID               116539 non-null  object
 1   Month                  142284 non-null  object
 2   Reported by            142284 non-null  object
 3   Falls within           142284 non-null  object
 4   Longitude              142284 non-null  float64
 5   Latitude               142284 non-null  float64
 6   Location               142284 non-null  object
 7   LSOA code              142284 non-null  object
 8   LSOA name              142284 non-null  object
 9   Crime type             142284 non-null  object
 10  Last outcome category  116539 non-null  object
 11  Context                0 non-null       float64
dtypes: float64(3), object(9)
memory usage: 13.0+ MB